server:
  port: 10000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: qa
          uri: http://192.168.101.232:8004
          predicates:
            - Switch=true
management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace