server:
  port: 10000
spring:
#  session:
#    store-type: redis
#  redis:
#    host: localhost
#    port: 6379
#    password:
  #  cloud:
#    gateway:
#      routes:
#        - id: add_request_header_route
#          uri: http://192.168.101.232:8000
#          filters:
#            - AddRequestHeader=Authorization
#          predicates:
#            - Switch=true
  security:
    oauth2:
      client:
        registration:
          qa:
            client-id: yibaoApp
#            client-id: yibaoApp2
            client-secret: yibaoAppSecret
#            authorization-grant-type: client_credentials
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/qa'
#            redirect-uri: '{baseUrl}/oauth2/authorization/qa'
#            redirect-uri: '{baseUrl}/login'
            scope: all
        provider:
          qa:
            user-info-uri: http://192.168.101.232:8000/principal
            authorization-uri: http://192.168.101.232:8000/oauth/authorize
            token-uri: http://192.168.101.232:8000/oauth/token
            user-name-attribute: name
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.101.232:8000/oauth/token_key
  application:
    name: gateway
# 此处路由需要启动后动态添加，这样，才能修改路由，实现启停
#  cloud:
#    gateway:
#      routes:
#        - id: baidu
#          uri: https://www.baidu.com
#          predicates:
#            - Switch=true

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO