server:
  port: 10000
spring:
  application:
    name: gateway
# 此处路由需要启动后动态添加，这样，才能修改路由，实现启停
#  cloud:
#    gateway:
#      routes:
#        - id: baidu
#          uri: https://www.baidu.com
#          predicates:
#            - Switch=true
management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace